### ISSUE TITLE
HTTP Request Error in Google App Engine

### ISSUE THREAD

**Issue by roykingtree** [CurrencyCloud/currencycloud-python#20]
For certain requests, like GET detailed rates, GAE throws a `ChunkedEncodingError`. I believe this can be fixed using monkeypatch (described [here](https://stackoverflow.com/questions/9604799/can-python-requests-library-be-used-on-google-app-engine) in the 2nd solution). 

So in config.py imports, you might be able to just add: 
`import requests`
`import requests_toolbelt.adapters.appengine`
`requests_toolbelt.adapters.appengine.monkeypatch()`

**Comment by EAddario** [comment]
Thanks for raising the issue and suggesting a solution Roy. We have discussed with the maintainers and after evaluating the pros and cons we have decided not to implement a fix for now.

We aim to target the widest possible set of use cases, and where possible we try to explicitly declare and isolate dependencies. Implementing the monkeypatch will break that principle for users not running on GAE.

You are however more than welcome to enhance the SDK for your particular needs.
