### ISSUE TITLE
CADRUB currency pair

### ISSUE THREAD

**Issue by roykingtree** [CurrencyCloud/currencycloud-python#22]
When getting basic rates, there is no rate for CADRUB, but there is a rate for USDRUB.

**Comment by roykingtree** [comment]
same issue with MXNRUB

**Comment by derikvercueil** [comment]
Hi @roykingtree the supported currency pairs are available on the following site: 

https://www.currencycloud.com/support/currency-pairs/

**Comment by roykingtree** [comment]
ah okay thanks
