### ISSUE TITLE
Types not respected everything is a string

### ISSUE THREAD

**Issue by cjstudioz** [CurrencyCloud/currencycloud-python#34]
Unsure if this is true for all results, using transactions as an example all number and date types are returned as strings. Appreciate this should be fixed in the upstream REST API but are there plans to resolve in python first?

```
import currencycloud as cc
client = cc.Client('yourid', 'yourapikey')
res = client.transactions.find()
trans = res[0]
print(type(trans.amount))
print(type(trans.settles_at))
```

**Comment by EAddario** [comment]
Hi @cjstudioz, the SDK's mapping of JSON to Python objects assumes string as default type to allow for maximum flexibility client-side across all the versions of Python we support (2.7 and onwards), but we recognise this approach eschews all the benefits of better (safer?) typing and expect to address by the time 2.7 reaches EOL or sooner.

Community contributions are also welcome :bowtie:

**Comment by cjstudioz** [comment]
Thanks, are you suggesting you'd be open to me augmenting the python SDK to cast the types appropriately in the python objects. This could potentially be breaking change if someone relies on them being strings. 

I will likely make changes in my own fork and you're welcome to merge them back into your repo should you wish. however, if you're open to accepting those changes, I will endeavor to make it easier for you to integrate but I also need to be commercial and practical with how much time I can spend on this

**Comment by EAddario** [comment]
We welcome all voluntary community feedback and enhancements. Our contribution guidelines are [available here](https://github.com/CurrencyCloud/currencycloud-python/blob/master/CONTRIBUTING.md)
