### ISSUE TITLE
Beneficiary.first fails if beneficiary not found

### ISSUE THREAD

**Issue by barroca** [CurrencyCloud/currencycloud-python#36]
The api beneficiary.first fails if no beneficiary is found because the code tries to access the index 0 
which is not present on the return:

```
def first(self, **params):
        params['per_page'] = 1
        return self.find(**params)[0]
```

maybe the code needs to change for:
```
def first(self, **params):
       params['per_page'] = 1
       beneficiaries = self.find(**params)
       return self.find(**params)[0] if len(beneficiaries) > 0 else None
```

**Comment by cjstudioz** [comment]
that can probably be better expressed as:

def first(self, **params):
       params['per_page'] = 1
       beneficiaries = self.find(**params)
       if beneficiaries:
            return beneficiaries[0]
      #else return None is implicit

**Comment by EAddario** [comment]
Hi @barroca, thank you for raising this issue! We should have deprecated all **_first_** methods some time ago as they were originally used in the early stages of the SDK development for testing. They simply return the first object without regards to any search parameter. OK for quick testing but of little to no use in production as our http endpoints do not guarantee sorting unless the **_order_** parameter is used.

If you require that behaviour, a better approach is to use `find(per_page=1)`
