### ISSUE TITLE
Library is not thread-safe and contains serious race conditions.

### ISSUE THREAD

**Issue by danielsamuels** [CurrencyCloud/currencycloud-python#5]
Due to the usage of [global variables](https://github.com/CurrencyCloud/currencycloud-python/blob/e0122c0ee6813caac45d2326b33d51d9f326f5fb/currencycloud/__init__.py#L21) in the session manager, and the fact that all requests to the API are made on a module-level this application is not thread-safe and the usage of `close_session` and `reset_session` will result in race conditions with disastrous consequences when used in multi-threaded environments.

A simple situation in which the global variables become a problem is when used in conjunction with web frameworks such as Django. In this configuration the first usage of the `currencycloud` library will result in that user being logged in for every subsequent request, regardless of whether `currencycloud.login_id` and `currencycloud.api_key` are modified.  As previously mentioned, there are a few session management methods available, namely `close_session` and `reset_session`. If these methods were used in a standard request-response flow the session could be reset and re-created in one thread while the library is being actively used in another. This would lead to both requests being made against the same user and therefore leading to an unacceptable data leakage across client accounts.

For version 1 of the CurrencyCloud API [I wrote a small library](https://gist.github.com/danielsamuels/666250682cd6737582b5) to handle the session state for users in a thread-safe way with the primary architecture decision made to use and instantiate new classes of the library on each request. This meant that the application views passed the active user into the library which then returned an isolated environment in which all operations would be executed locally to that user.  This was only possible because it was written in a OOP style. In contrast, by having all of the methods and state stored at a module level in this library, it is incredibly vulnerable to all of the problems listed above.

I would strongly advise you to warn users about these vulnerabilities and recommend that this library is not used in any production code until these issues are resolved. I believe that this library will require a partial or full rewrite to be considered production-ready.  I am aware that this library is marked as 'pre-alpha', but it is listed as the official API on the company Github account and as such, this is not obvious.

Thanks,
Daniel Samuels

Lead Developer at Onespacemedia

**Comment by rjnienaber** [comment]
Thank you for bringing this to our attention. We will start on getting this threading issue fixed. The intention behind the SDK was to only have one api key/login per instance of the application. While we think this is okay for authenticating against the api, we can see that this [same mechanism is used for on_behalf_of](https://github.com/CurrencyCloud/currencycloud-python/blob/e0122c0ee6813caac45d2326b33d51d9f326f5fb/currencycloud/__init__.py#L53). This will lead to problems as you correctly point out so we will fix this bug.

The alternative way of specifying `on_behalf_of` should still work:

```python
currencycloud.Account.create(account_name='My Test User', on_behalf_of='c6ece846-6df1-461d-acaa-b42a6aa74045')
```

This should bypass the global session and treat it like a normal parameter.

**Comment by danielsamuels** [comment]
No problem. I've gone through and updated the majority of our application code to use `on_behalf_of`. One thing I have noticed however is that none of the `retrieve` endpoints allow for it to be passed through, even though it's listed as an optional parameter in the options, and does work when using bare HTTP requests.  Is this a bug in the library, or does it not need to be passed for those endpoints?

**Comment by rjnienaber** [comment]
Fyi @danielsamuels, I've created #7 for the retrieve problem you highlighted in your last comment.
