### ISSUE TITLE
We need a new version on PyPI

### ISSUE THREAD

**Issue by danielquinn** [CurrencyCloud/currencycloud-python#8]
[PyPI is still hosting 0.7.0](https://pypi.python.org/pypi/currencycloud) which doesn't include the domain name change.  

```bash
$ wget https://pypi.python.org/packages/02/35/d050bea78de5c38e321bf9d166efba1da856e27fad063ad63b29bf48ff08/currencycloud-0.7.0.tar.gz
$ tar xzf currencycloud-0.7.0.tar.gz
$ grep -r thecurrencycloud.com currencycloud-0.7.0/currencycloud/config.py 
  ENV_PRODUCTION: 'https://api.thecurrencycloud.com',
  ENV_DEMOSTRATION: 'https://devapi.thecurrencycloud.com',
```

Git master is listed as failing the build, and no new development has been done since February, and I keep hearing that you lot are planning on turning off the old domain any day now so... what's going on?

**Comment by ollierattue** [comment]
Also need the new version on PyPI. What is the schedule here?

**Comment by EAddario** [comment]
v2.2.0 should be available in PyPI shortly.

Please be aware that the correct package name is now [currency-cloud](https://pypi.org/project/currency-cloud/) and **not** currencycloud

**Comment by EAddario** [comment]
Available in PyPI...
